title: Vedant Chandra
logo: /vedantchandra.github.io/assets/headshot.jpg
description: Center for Astrophysics, Harvard & Smithsonian
theme: jekyll-theme-minimal
baseurl: /vedantchandra.github.io
google_analytics: G-XX2JYW4JXH